Repository Rising-Star-DX/contract-ai-partner-ai, pull requests merged in 2025-04, with the labels that each got.

#76 Refactor/deploy/setting
  app/__init__.py
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/standard/standard_blueprint.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/prompt_service.py
  app/services/standard/vector_delete.py
  app/services/standard/vector_store.py
Labels: 🐛FIX

#80 Feat/chunking
  app/clients/openai_clients.py
  app/schemas/chunk_schema.py
  app/services/common/chunking_service.py
  app/services/common/embedding_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/prompt_service.py
  app/services/standard/vector_store.py
  requirements.txt
Labels: ✨FEAT

#81 Change/response
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/standard/standard_blueprint.py
  app/common/constants.py
  app/common/file_type.py
  app/models/vector.py
  app/schemas/analysis_response.py
  app/schemas/document_request.py
  app/services/agreement/img_service.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/ingestion_pipeline.py
  app/services/common/prompt_service.py
  app/services/standard/vector_store.py
Labels: ✨FEAT, 🛠️REFACTOR

#82 Refactor/optimize/openai
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/common/async_loop.py
  app/blueprints/standard/standard_blueprint.py
  app/common/exception/error_code.py
  app/schemas/analysis_response.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/chunking_service.py
  app/services/common/embedding_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/pdf_service.py
  app/services/common/prompt_service.py
  app/services/common/s3_service.py
  app/services/standard/vector_store.py
Labels: 🛠️REFACTOR

#88 Feat/legal word/save search
  .github/workflows/deploy.yml
  app/__init__.py
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/standard/standard_blueprint.py
  app/common/decorators.py
  app/models/vector.py
  app/schemas/analysis_response.py
  app/schemas/chunk_schema.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/chunking_service.py
  app/services/common/embedding_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/llm_retry.py
  app/services/common/prompt_service.py
  app/services/common/qdrant_utils.py
  app/services/standard/vector_store.py
  app/services/standard/vector_store/__init__.py
  app/services/standard/vector_store/payload_builder.py
  app/services/standard/vector_store/vector_processor.py
  requirements.txt
Labels: ✨FEAT

#90 Feat/intergration
  .github/workflows/deploy.yml
  Dockerfile
  app/common/constants.py
  app/schemas/analysis_response.py
  app/schemas/chunk_schema.py
  app/services/agreement/ocr_service.py
  app/services/agreement/vectorize_similarity.py
  app/services/agreement/vision_service.py
  app/services/common/chunking_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/prompt_service.py
  requirements.txt
Labels: 📱FUNC
