Repository Rising-Star-DX/contract-ai-partner-ai, pull requests merged in 2025-03, with the labels that each got.

#16 Feat/reference document/vector db
  app/__init__.py
  app/blueprints/contract_review/__init__.py
  app/blueprints/contract_review/controller.py
  app/blueprints/contract_review/routes.py
  app/blueprints/contracts/controller.py
  app/blueprints/document_management/reference_document.py
  app/blueprints/document_management/routes.py
  app/models/document_models.py
  app/services/chunking.py
  app/services/document_management/reference_document_service.py
  app/services/embedding.py
  app/services/example.py
  app/services/vector_db.py
  app/services/vector_store.py
  requirements.txt
Labels: ✨FEAT

#19 ✔️ Feat/common/clean code
  .gitignore
  app/__init__.py
  app/blueprints/__init__.py
  app/blueprints/agreement/__init__.py
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/agreement/agreement_exception.py
  app/blueprints/document_management/reference_document.py
  app/blueprints/standard/__init__.py
  app/blueprints/standard/standard_blueprint.py
  app/blueprints/standard/standard_exception.py
  app/common/__init__.py
  app/common/exception/__init__.py
  app/common/exception/custom_exception.py
  app/common/exception/error_code.py
  app/common/exception/error_handler.py
  app/models/__init__.py
  app/models/vector.py
  app/schemas/__init__.py
  app/schemas/chunk_schema.py
  app/schemas/error_response.py
  app/schemas/pdf_request.py
  app/schemas/success_code.py
  app/schemas/success_response.py
  app/services/__init__.py
  app/services/agreement/__init__.py
  app/services/common/__init__.py
  app/services/common/chunking_service.py
  app/services/common/pdf_service.py
  app/services/common/s3_service.py
  app/services/document_management/reference_document_service.py
  app/services/standard/__init__.py
  app/services/standard/processor.py
  app/services/standard/vector_store.py
  app/utils/__init__.py
  config/__init__.py
  requirements.txt
Labels: 🛠️REFACTOR

#21 Fix/error/handling
  .gitignore
  app/common/exception/error_code.py
  app/common/exception/error_handler.py
  app/services/common/pdf_service.py
  app/services/common/s3_service.py
  app/services/standard/processor.py
  app/services/standard/vector_store.py
Labels: 🐛FIX

#22 Feat/change/to azure
  app/__init__.py
  app/blueprints/standard/standard_blueprint.py
  app/clients/__init__.py
  app/clients/openai_clients.py
  app/common/exception/error_code.py
  app/common/exception/error_handler.py
  app/containers/__init__.py
  app/containers/service_container.py
  app/services/common/embedding_service.py
  app/services/common/prompt_service.py
  app/services/standard/processor.py
  app/services/standard/vector_store.py
  app/utils/__init__.py
  app/utils/file_handler.py
  requirements.txt
Labels: ✨FEAT

#24 Feat/optimize/chunking and prompt
  .gitignore
  app/__init__.py
  app/blueprints/standard/standard_blueprint.py
  app/schemas/chunk_schema.py
  app/services/common/chunking_service.py
  app/services/common/prompt_service.py
  app/services/common/s3_service.py
  app/services/standard/processor.py
  app/services/standard/vector_store.py
  config/__init__.py
  config/app_config.py
  config/s3_config.py
Labels: 🛠️REFACTOR

#26 Feat/standard/delete
  app/__init__.py
  app/blueprints/standard/standard_blueprint.py
  app/clients/qdrant_client.py
  app/common/exception/error_code.py
  app/models/vector.py
  app/schemas/success_code.py
  app/services/standard/vector_delete.py
  app/services/standard/vector_store.py
  requirements.txt
Labels: ✨FEAT

#33 Feat/agreement/ocr image #28
  Dockerfile
  app/__init__.py
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/standard/standard_blueprint.py
  app/clients/openai_clients.py
  app/common/exception/error_code.py
  app/common/exception/error_handler.py
  app/containers/service_container.py
  app/schemas/document_request.py
  app/schemas/pdf_request.py
  app/schemas/success_code.py
  app/services/agreement/img_service.py
  app/services/agreement/processor.py
  app/services/agreement/vectorize_similarity.py
  app/services/agreement/vision_service.py
  app/services/common/pdf_service.py
  app/services/common/processor.py
  app/services/common/s3_service.py
  app/services/standard/vector_delete.py
  app/services/standard/vector_store.py
  requirements.txt
Labels: ✨FEAT

#42 Refactor/agreeement/structure
  app/__init__.py
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/standard/standard_blueprint.py
  app/common/exception/error_code.py
  app/common/exception/error_handler.py
  app/schemas/analysis_response.py
  app/schemas/success_code.py
  app/schemas/success_response.py
  app/services/agreement/img_service.py
  app/services/agreement/processor.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/embedding_service.py
  app/services/common/pdf_service.py
  app/services/common/processor.py
  app/services/standard/vector_delete.py
  app/services/standard/vector_store.py
  requirements.txt
Labels: 🛠️REFACTOR

#44 Refactor/standard
  app/blueprints/standard/standard_blueprint.py
  app/clients/openai_clients.py
  app/common/constants.py
  app/common/exception/error_code.py
  app/containers/service_container.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/processor.py
  app/services/common/prompt_service.py
  app/services/common/text_processing_service.py
  app/services/standard/vector_delete.py
  app/services/standard/vector_store.py
Labels: 📱FUNC

#48 🎨 s3 url -> 객체 url 변경
  app/services/common/pdf_service.py
  app/services/common/processor.py
  app/services/common/s3_service.py
Labels: 🛠️REFACTOR

#51 Async/agreement
  app/__init__.py
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/standard/standard_blueprint.py
  app/clients/qdrant_client.py
  app/common/file_type.py
  app/schemas/analysis_response.py
  app/schemas/chunk_schema.py
  app/schemas/document.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/chunking_service.py
  app/services/common/embedding_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/pdf_service.py
  app/services/common/processor.py
  app/services/common/prompt_service.py
  app/services/common/s3_service.py
  app/services/common/text_processing_service.py
  app/services/standard/vector_store.py
  requirements.txt
Labels: 🛠️REFACTOR

#52 Refactor/agreement/dto
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/standard/standard_blueprint.py
  app/clients/openai_clients.py
  app/containers/service_container.py
  app/schemas/analysis_response.py
  app/schemas/chunk_schema.py
  app/schemas/document.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/chunking_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/pdf_service.py
  app/services/common/prompt_service.py
  app/services/common/text_processing_service.py
  app/services/standard/vector_delete.py
  app/services/standard/vector_store.py
Labels: 🛠️REFACTOR

#55 Async/solution
  app/blueprints/agreement/agreement_blueprint.py
  app/clients/openai_clients.py
  app/containers/service_container.py
  app/schemas/chunk_schema.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/chunking_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/pdf_service.py
  app/services/common/prompt_service.py
Labels: 📱FUNC

#54 Fix/deploy/async
  app/blueprints/agreement/agreement_blueprint.py
  app/blueprints/common/async_loop.py
  app/blueprints/standard/standard_blueprint.py
  app/common/constants.py
  app/containers/service_container.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/embedding_service.py
  app/services/common/prompt_service.py
  config/app_config.py
Labels: 🐛FIX

#60 Refactor/agreement/response
  app/blueprints/agreement/agreement_blueprint.py
  app/clients/qdrant_client.py
  app/common/constants.py
  app/schemas/analysis_response.py
  app/schemas/success_response.py
  app/services/agreement/vectorize_similarity.py
  app/services/common/chunking_service.py
  app/services/common/ingestion_pipeline.py
  app/services/common/prompt_service.py
  requirements.txt
Labels: ✨FEAT, 🛠️REFACTOR

#66 Feat/ocr
  app/services/agreement/vectorize_similarity.py
  app/services/common/prompt_service.py
Labels: ✨FEAT
